const CN_AUTH={
  usersKey:'cn-users-v1',sessionKey:'cn-session-v1',
  users(){try{return JSON.parse(localStorage.getItem(this.usersKey)||'[]')}catch{return[]}},
  saveUsers(v){localStorage.setItem(this.usersKey,JSON.stringify(v))},
  session(){try{return JSON.parse(localStorage.getItem(this.sessionKey)||'null')}catch{return null}},
  setSession(v){v?localStorage.setItem(this.sessionKey,JSON.stringify(v)):localStorage.removeItem(this.sessionKey)},
  async hash(s){const data=new TextEncoder().encode(s);const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')},
  normalizeEmail(s){return String(s||'').trim().toLowerCase()},
  current(){const ses=this.session();if(!ses)return null;return this.users().find(u=>u.id===ses.userId)||null},
  async register(data){const users=this.users(),email=this.normalizeEmail(data.email);if(users.some(u=>u.email===email))throw new Error('Já existe uma conta com este e-mail.');const user={id:'u_'+Date.now()+'_'+Math.random().toString(36).slice(2,8),name:data.name.trim(),email,phone:data.phone.trim(),type:data.type,cpf:data.type==='pf'?data.document.trim():'',cnpj:data.type==='pj'?data.document.trim():'',company:data.type==='pj'?data.company.trim():'',pjStatus:data.type==='pj'?'Cadastro PJ em análise':'Não se aplica',passwordHash:await this.hash(data.password),createdAt:new Date().toISOString()};users.push(user);this.saveUsers(users);this.setSession({userId:user.id,at:Date.now()});return user},
  async login(email,password){email=this.normalizeEmail(email);const user=this.users().find(u=>u.email===email);if(!user||user.passwordHash!==await this.hash(password))throw new Error('E-mail ou senha incorretos.');this.setSession({userId:user.id,at:Date.now()});return user},
  logout(){this.setSession(null);location.href='index.html'},
  update(id,patch){const users=this.users(),i=users.findIndex(u=>u.id===id);if(i<0)return null;users[i]={...users[i],...patch};this.saveUsers(users);return users[i]}
};
function cnEscape(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function renderAccountHeader(){document.querySelectorAll('.account-slot').forEach(slot=>{const u=CN_AUTH.current();slot.innerHTML=u?`<a class="account-pill account-pill--signed" href="conta.html"><span class="account-avatar">${cnEscape((u.name||'C').trim().charAt(0).toUpperCase())}</span><span><small>Olá,</small><b>${cnEscape((u.name||'Cliente').split(' ')[0])}</b></span></a>`:`<a class="account-pill" href="login.html"><span class="account-icon">👤</span><span><small>Minha conta</small><b>Entrar</b></span></a>`})}
function initLogin(){const f=document.querySelector('#loginForm');if(!f)return;if(CN_AUTH.current()){location.href='conta.html';return}f.addEventListener('submit',async e=>{e.preventDefault();const err=document.querySelector('#authError');err.textContent='';try{await CN_AUTH.login(f.email.value,f.password.value);location.href='conta.html'}catch(x){err.textContent=x.message}})}
function initRegister(){const f=document.querySelector('#registerForm');if(!f)return;const typeEls=[...f.querySelectorAll('[name=type]')],pj=document.querySelector('#pjFields'),docLabel=document.querySelector('#docLabel'),company=document.querySelector('#company');function draw(){const type=f.querySelector('[name=type]:checked').value;pj.hidden=type!=='pj';docLabel.textContent=type==='pj'?'CNPJ':'CPF';company.required=type==='pj'}typeEls.forEach(x=>x.addEventListener('change',draw));draw();f.addEventListener('submit',async e=>{e.preventDefault();const err=document.querySelector('#authError');err.textContent='';if(f.password.value.length<6){err.textContent='A senha deve ter pelo menos 6 caracteres.';return}if(f.password.value!==f.confirm.value){err.textContent='As senhas não coincidem.';return}try{await CN_AUTH.register({name:f.name.value,email:f.email.value,phone:f.phone.value,type:f.querySelector('[name=type]:checked').value,document:f.document.value,company:f.company.value,password:f.password.value});location.href='conta.html'}catch(x){err.textContent=x.message}})}
function initAccount(){const host=document.querySelector('#accountDashboard');if(!host)return;const u=CN_AUTH.current();if(!u){location.href='login.html';return}document.querySelector('#accountName').textContent=u.name;document.querySelector('#accountType').textContent=u.type==='pj'?'Conta empresarial':'Conta pessoal';document.querySelector('#pjStatusText').textContent=u.pjStatus;document.querySelector('#profileForm').name.value=u.name||'';document.querySelector('#profileForm').email.value=u.email||'';document.querySelector('#profileForm').phone.value=u.phone||'';document.querySelector('#profileForm').document.value=u.type==='pj'?u.cnpj:u.cpf;document.querySelector('#profileForm').company.value=u.company||'';document.querySelector('#companyField').hidden=u.type!=='pj';document.querySelector('#profileForm').addEventListener('submit',e=>{e.preventDefault();CN_AUTH.update(u.id,{name:e.currentTarget.name.value.trim(),phone:e.currentTarget.phone.value.trim(),company:e.currentTarget.company.value.trim()});renderAccountHeader();const ok=document.querySelector('#profileSaved');ok.textContent='Dados atualizados com sucesso.';setTimeout(()=>ok.textContent='',2500)});document.querySelector('#logoutBtn').addEventListener('click',()=>CN_AUTH.logout());const cart=JSON.parse(localStorage.getItem('cn-cart')||'[]');document.querySelector('#accountCartCount').textContent=cart.reduce((n,x)=>n+(Number(x.qty)||1),0)}
document.addEventListener('DOMContentLoaded',()=>{renderAccountHeader();initLogin();initRegister();initAccount()});
