
const PHONE='556120990229';
let products=[];let cart=JSON.parse(localStorage.getItem('cn-cart')||'[]');let favorites=JSON.parse(localStorage.getItem('cn-favorites')||'[]');
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function save(){localStorage.setItem('cn-cart',JSON.stringify(cart));localStorage.setItem('cn-favorites',JSON.stringify(favorites));updateCartCount();renderCart()}
function updateCartCount(){const c=$('#cartCount');if(c)c.textContent=cart.length}
function openCart(){const d=$('#cartDrawer'),b=$('#backdrop');if(d){d.classList.add('open');d.setAttribute('aria-hidden','false')}if(b)b.classList.add('open');document.body.style.overflow='hidden'}
function closeCart(){const d=$('#cartDrawer'),b=$('#backdrop');if(d){d.classList.remove('open');d.setAttribute('aria-hidden','true')}if(b)b.classList.remove('open');document.body.style.overflow=''}
function addCart(id){if(!cart.includes(id)){cart.push(id);toast('Produto adicionado à lista de cotação.')}else toast('Este produto já está na sua lista.');save()}
function removeCart(id){cart=cart.filter(x=>x!==id);save()}
function toggleFavorite(id,btn){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();if(btn)btn.classList.toggle('active');toast(favorites.includes(id)?'Produto salvo nos favoritos.':'Produto removido dos favoritos.')}
function renderCart(){const box=$('#cartItems'),empty=$('#cartEmpty');if(!box)return;box.innerHTML='';const selected=products.filter(p=>cart.includes(p.id));if(empty)empty.style.display=selected.length?'none':'block';selected.forEach(p=>{box.insertAdjacentHTML('beforeend',`<div class="cart-item"><img src="assets/products/${p.image}.svg" alt=""><div><b>${p.name}</b><small>${p.brand}</small></div><button data-remove="${p.id}" aria-label="Remover">×</button></div>`)})}
function productCard(p){return `<article class="product-card reveal"><div class="product-card__media" data-view="${p.id}"><img src="assets/products/${p.image}.svg" alt="Ilustração de ${p.name}" loading="lazy">${p.badge?`<span class="product-card__badge">${p.badge}</span>`:''}<button class="favorite ${favorites.includes(p.id)?'active':''}" data-fav="${p.id}" aria-label="Favoritar">♡</button></div><div class="product-card__body"><span class="product-brand">${p.brand} · ${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-actions"><button class="add-cart" data-add="${p.id}">Adicionar à cotação</button><button class="quick-view" data-view="${p.id}" aria-label="Ver detalhes">↗</button></div></div></article>`}
function initCatalog(){const grid=$('#productGrid');if(!grid)return;const search=$('#searchInput');const filters=$('#filters');const count=$('#resultCount');const limit=Number(grid.dataset.limit||0);const cats=['Todos',...new Set(products.map(p=>p.category))];let active='Todos';if(filters)filters.innerHTML=cats.map(c=>`<button class="filter-btn ${c==='Todos'?'active':''}" data-filter="${c}">${c}</button>`).join('');function draw(){const q=(search?.value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let list=products.filter(p=>active==='Todos'||p.category===active).filter(p=>`${p.name} ${p.brand} ${p.category} ${p.desc}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(q));if(limit)list=list.slice(0,limit);grid.innerHTML=list.length?list.map(productCard).join(''):'<div class="no-results"><b>Nenhum produto encontrado.</b><p>Tente outro termo ou categoria.</p></div>';if(count)count.textContent=list.length;observeReveals()};filters?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;active=b.dataset.filter;$$('.filter-btn',filters).forEach(x=>x.classList.toggle('active',x===b));draw()});search?.addEventListener('input',draw);draw()}
function openProduct(id){const p=products.find(x=>x.id===id),m=$('#productModal'),content=$('#productModalContent');if(!p||!m||!content)return;content.innerHTML=`<div class="modal-product"><div class="modal-product__media"><img src="assets/products/${p.image}.svg" alt="Ilustração de ${p.name}"></div><div class="modal-product__content"><span class="product-brand">${p.brand} · ${p.category}</span><h2>${p.name}</h2><div class="tabs"><button class="tab active" data-tab="desc">Descrição</button><button class="tab" data-tab="var">Variações</button><button class="tab" data-tab="att">Atendimento</button></div><div class="tab-pane active" data-pane="desc"><p>${p.desc}</p><p>Produto apresentado para composição de catálogo e cotação. Confirme marca, modelo, especificações e disponibilidade com a equipe comercial.</p></div><div class="tab-pane" data-pane="var"><p><strong>Opções:</strong> ${p.variations}</p><p>Podemos preparar uma proposta de acordo com volume, cidade de entrega e perfil da compra.</p></div><div class="tab-pane" data-pane="att"><p>Adicione este item à sua lista e envie uma solicitação. A equipe comercial retornará para confirmar quantidades e condições.</p></div><button class="btn btn--yellow full" data-add="${p.id}">Adicionar à cotação</button></div></div>`;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeProduct(){const m=$('#productModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}document.body.style.overflow=''}
function sendQuote(){const selected=products.filter(p=>cart.includes(p.id));if(!selected.length){toast('Adicione pelo menos um produto.');return}const name=$('#quoteName')?.value.trim()||'Não informado';const doc=$('#quoteDoc')?.value.trim()||'Não informado';const notes=$('#quoteNotes')?.value.trim()||'Sem observações';const items=selected.map((p,i)=>`${i+1}. ${p.name} — ${p.brand}`).join('\n');const text=`Olá, gostaria de solicitar uma cotação na Casa Nova Distribuidora.\n\nNome/empresa: ${name}\nCPF/CNPJ: ${doc}\n\nProdutos:\n${items}\n\nObservações: ${notes}`;window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`,'_blank')}
function formToWhatsApp(form,title){form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);let text=`${title}\n\n`;for(const [k,v] of data.entries())if(v)text+=`${k}: ${v}\n`;window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`,'_blank');toast('Abrindo o atendimento com os dados preenchidos.')})}
function observeReveals(){const els=$$('.reveal:not(.visible)');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('visible');io.unobserve(en.target)}}),{threshold:.08});els.forEach(e=>io.observe(e))}
function countUp(){const els=$$('[data-count]');if(!els.length)return;const io=new IntersectionObserver(entries=>entries.forEach(en=>{if(!en.isIntersecting)return;const el=en.target,end=Number(el.dataset.count),suffix=el.dataset.suffix||'';let start=0;const dur=1200,st=performance.now();function step(now){const p=Math.min((now-st)/dur,1);el.textContent=Math.floor(end*(1-Math.pow(1-p,3)))+suffix;if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step);io.unobserve(el)}),{threshold:.6});els.forEach(e=>io.observe(e))}
function initFaq(){$$('.faq-question').forEach(b=>b.addEventListener('click',()=>b.closest('.faq-item').classList.toggle('open')))}
function markActiveNav(){const page=location.pathname.split('/').pop()||'index.html';$$('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===page))}
async function boot(){try{products=window.CN_PRODUCTS||await fetch('products.json').then(r=>r.json())}catch(e){console.error(e);products=[]}markActiveNav();initCatalog();renderCart();updateCartCount();observeReveals();countUp();initFaq();$$('form[data-whatsapp]').forEach(f=>formToWhatsApp(f,f.dataset.title||'Solicitação pelo site'));}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){addCart(Number(add.dataset.add));return}const view=e.target.closest('[data-view]');if(view&&!e.target.closest('[data-fav]')){openProduct(Number(view.dataset.view));return}const fav=e.target.closest('[data-fav]');if(fav){e.stopPropagation();toggleFavorite(Number(fav.dataset.fav),fav);return}const rem=e.target.closest('[data-remove]');if(rem){removeCart(Number(rem.dataset.remove));return}const tab=e.target.closest('[data-tab]');if(tab){const content=tab.closest('.modal-product__content');$$('.tab',content).forEach(t=>t.classList.toggle('active',t===tab));$$('.tab-pane',content).forEach(p=>p.classList.toggle('active',p.dataset.pane===tab.dataset.tab));return}});
$('#menuToggle')?.addEventListener('click',e=>{const n=$('#mainNav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
$$('.js-open-cart').forEach(b=>b.addEventListener('click',openCart));$('#closeCart')?.addEventListener('click',closeCart);$('#backdrop')?.addEventListener('click',closeCart);$('#sendQuote')?.addEventListener('click',sendQuote);$('#clearCart')?.addEventListener('click',()=>{cart=[];save();toast('Lista limpa.')});$('#closeProductModal')?.addEventListener('click',closeProduct);$('#productModal')?.addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});window.addEventListener('scroll',()=>$('.header')?.classList.toggle('scrolled',scrollY>15));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeProduct()}});boot();


// Máquinas: pré-preenchimento e envio de solicitação
function scrollToMachineForm(machine='', mode=''){
  const form=document.querySelector('#machineForm');
  if(!form){ location.href=`maquinas.html?maquina=${encodeURIComponent(machine)}&modalidade=${encodeURIComponent(mode)}`; return; }
  const ms=document.querySelector('#machineSelect'), mm=document.querySelector('#machineMode');
  if(ms && machine){ const opt=[...ms.options].find(o=>o.text.toLowerCase().includes(machine.toLowerCase().split(' ')[0])); if(opt)ms.value=opt.value; }
  if(mm && mode){ const opt=[...mm.options].find(o=>o.text.toLowerCase().includes(mode.toLowerCase().split(' ')[0])); if(opt)mm.value=opt.value; }
  document.querySelector('#solicitar')?.scrollIntoView({behavior:'smooth',block:'start'});
  setTimeout(()=>form.querySelector('input,select')?.focus({preventScroll:true}),650);
}
document.addEventListener('click',e=>{
  const a=e.target.closest('.machine-action');if(a){scrollToMachineForm(a.dataset.machine||'',a.dataset.mode||'');return}
  const m=e.target.closest('.machine-mode');if(m){scrollToMachineForm('',m.dataset.mode||'');return}
});
const machineForm=document.querySelector('#machineForm');
if(machineForm){
  const params=new URLSearchParams(location.search);const q=params.get('maquina')||'';const map={escavadeira:'Escavadeira hidráulica',empilhadeira:'Empilhadeira',retroescavadeira:'Retroescavadeira'};if(q&&map[q])document.querySelector('#machineSelect').value=map[q];
  machineForm.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(machineForm);let text='Olá, vim pelo site da Casa Nova e gostaria de atendimento sobre máquinas e equipamentos.\n\n';for(const [k,v] of data.entries())if(String(v).trim())text+=`${k}: ${v}\n`;window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(text)}`,'_blank');toast('Abrindo o WhatsApp com sua solicitação.')});
}
